/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package megadownload;

import java.io.File;
import java.io.IOException;
import java.net.ConnectException;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import megadownload.Connection.Connection;
import megadownload.Connection.ConnectionID;
import megadownload.Connection.TCPConnection;
import megadownload.Exceptions.ConnectionsException;
import megadownload.Exceptions.LoggerException;
import megadownload.Threads.ServerThread;
import megadownload.Utils.ByteFile;
import megadownload.Utils.Crypto;
import megadownload.Utils.Logging;

/**
 *
 * @author Ganet
 */
public class MegaDownloadUI extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public MegaDownloadUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        title = new javax.swing.JLabel();
        ip = new javax.swing.JLabel();
        ipEdit = new javax.swing.JTextField();
        port = new javax.swing.JLabel();
        portEdit = new javax.swing.JTextField();
        buttonSend = new javax.swing.JButton();
        buttonFile = new javax.swing.JButton();
        textFile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("MEGADOWNLOAD");

        ip.setText("Dirección IP");

        ipEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipEditActionPerformed(evt);
            }
        });

        port.setText("Puerto");

        portEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portEditActionPerformed(evt);
            }
        });

        buttonSend.setText("Enviar");
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });

        buttonFile.setText("Selecciona Fichero:");
        buttonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFileActionPerformed(evt);
            }
        });

        textFile.setText("No hay ningún fichero seleccionado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ipEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(port)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(portEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFile, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addComponent(buttonSend)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ip)
                            .addComponent(ipEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(portEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(port, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonFile)
                            .addComponent(textFile)))
                    .addComponent(buttonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void portEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portEditActionPerformed

    private void ipEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipEditActionPerformed

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        ByteFile byteFile = null;
        Socket sock = null;
        try {
            byteFile = new ByteFile (file);
            sock = new Socket(ipEdit.getText(), Integer.parseInt(portEdit.getText()));
        } catch (ConnectException ex) {
            JOptionPane.showMessageDialog(this, "Conexión rechazada");
            log.log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            JOptionPane.showMessageDialog(this, "Host desconocido. Asegurate que la dirección es correcta");
            log.log(Level.SEVERE, null, ex);            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
            log.log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Selecciona fichero");
            log.log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error recuperando números. Asegurate de que la dirección IP y el puerto no contienen letras");
            log.log(Level.SEVERE, null, ex);
        } 
        
        Connection con = new TCPConnection(new ConnectionID(byteFile.fileName()), sock);
        try {
            
            con.send(Crypto.encrypt(byteFile));
        } catch (ConnectionsException ex) {
            log.log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_buttonSendActionPerformed

    private void buttonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFileActionPerformed
        int returnVal = fileChooser.showOpenDialog(MegaDownloadUI.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
                file = fileChooser.getSelectedFile();
                //This is where a real application would open the file.
                textFile.setText(file.getName());
            } else {
                
            }
    }//GEN-LAST:event_buttonFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MegaDownloadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MegaDownloadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MegaDownloadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MegaDownloadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MegaDownloadUI().setVisible(true);
            }
        });
        
        ServerThread serverThread = null;
        try {
            Logger log = Logging.setupLog("MegaDownloadUI");
            serverThread = new ServerThread("ServerThread", Logging.setupLog("ServerThread"));
        } catch (LoggerException ex) {
            log.log(Level.SEVERE, null, ex);
        }
        serverThread.start();
    }
    
    private File file;
    private static Logger log;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFile;
    private javax.swing.JButton buttonSend;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel ip;
    private javax.swing.JTextField ipEdit;
    private javax.swing.JLabel port;
    private javax.swing.JTextField portEdit;
    private javax.swing.JLabel textFile;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
